"""create logistics schema

Revision ID: 91b71793c2e0
Revises: 
Create Date: 2026-09-28 23:30:32.769603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b71793c2e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FLEET_MANAGER', 'DRIVER', 'CUSTOMER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('license_number', sa.String(length=40), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_DELIVERY', 'OFFLINE', 'INACTIVE', name='driver_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_drivers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('license_number', name=op.f('uq_drivers_license_number')),
    sa.UniqueConstraint('user_id', name=op.f('uq_drivers_user_id'))
    )
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'IN_SERVICE', 'MAINTENANCE', 'INACTIVE', name='vehicle_status'), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_vehicles_driver_id_drivers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('vehicle_number', name=op.f('uq_vehicles_vehicle_number'))
    )
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tracking_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('pickup_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('delivery_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('package_description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'EXPRESS', name='shipment_priority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'ARRIVING', 'DELIVERED', 'FAILED', 'CANCELLED', name='shipment_status'), nullable=False),
    sa.Column('assigned_driver_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['drivers.id'], name=op.f('fk_shipments_assigned_driver_id_drivers')),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], name=op.f('fk_shipments_assigned_vehicle_id_vehicles')),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_shipments_customer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments')),
    sa.UniqueConstraint('tracking_number', name=op.f('uq_shipments_tracking_number'))
    )
    op.create_index(op.f('ix_shipments_assigned_driver_id'), 'shipments', ['assigned_driver_id'], unique=False)
    op.create_index(op.f('ix_shipments_assigned_vehicle_id'), 'shipments', ['assigned_vehicle_id'], unique=False)
    op.create_index(op.f('ix_shipments_customer_id'), 'shipments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'ARRIVING', 'DELIVERED', 'FAILED', 'CANCELLED', name='shipment_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_deliveries_driver_id_drivers')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_deliveries_shipment_id_shipments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_deliveries_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('shipment_id', name=op.f('uq_deliveries_shipment_id'))
    )
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_customer_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_assigned_vehicle_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_assigned_driver_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    bind = op.get_bind()
    for enum_name in (
        "shipment_status",
        "shipment_priority",
        "vehicle_status",
        "driver_status",
        "user_role",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
